### ISSUE TITLE
gradle build 失败

### ISSUE THREAD

**Issue by DaY1zz** [FudanSELab/Serverless_trainticket#1]
我在创建关于数据库初始化方法的Docker镜像时(执行part01_DataBaseDeployment.sh)，报错表示项目里面没有**model**模块
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':function:compileJava'.
> Could not resolve all task dependencies for configuration ':function:compileClasspath'.
   > Could not resolve project :model.
     Required by:
         project :function
      > Unable to find a matching configuration of project :model:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
```

看了一下initDatabaseFunctions文件夹下的每个项目的源码，的确没有model模块
所以build.gradle文件里面这个`compile project(':model')`应该是有问题的吧

![image](https://user-images.githubusercontent.com/66411125/174570083-8c8c92cf-4949-478e-a704-f4f7b199d2c4.png)

作者可以解答回复一下吗？虽然时间有点久远了。。

**Comment by AkasakaIsami** [comment]
您好，很高兴收到您的提问，感谢您为本项目提出的问题！

首先，在编写项目源码时，我直接使用了 OpenFaaS 官方所提供的 Java 8 函数模版，您所报错的文件中除去对jackson与mongodb driver的依赖是我自己添加的以外，没有编辑过其余部分。

我查阅了目前由OpenFaaS官方提供的 [Java 11 函数模版](https://github.com/openfaas/templates/blob/master/template/java11/function/build.gradle)，观察到您报错的语句已经被替换成如下代码（关注第17-18行）：
```
    compile 'com.openfaas:model:0.1.1'
    compile 'com.openfaas:entrypoint:0.1.0'
```

因此我认为这可能是由于OpenFaaS版本原因所导致的问题。serverless-trainticket的开发基于0.12.4版本的OpenFaaS，您可以针对您使用的OpenFaaS的版本，对函数模版作出相应修改（例如，将报错语句替换为上述代码）。

如果您还有后续问题，欢迎继续提问，我会帮助解决问题，谢谢！

***

Hi, thanks for your asking. I'm glad to help you with your problem.

First of all, I directly used the official Java 8 function template provided by OpenFaaS during the development, and I did not edit the rest of the file `build.gradle` except for adding the dependencies of jackson and mongodb driver.

I check the official [Java 11 function template](https://github.com/openfaas/templates/blob/master/template/java11/function/build.gradle) currently provided by OpenFaaS and find that the statement `compile project(':model')` has been replaced with the following statements (focus on lines 17-18).
```
    compile 'com.openfaas:model:0.1.1'
    compile 'com.openfaas:entrypoint:0.1.0'
```

So I think this is probably due to the OpenFaaS version. Serverless-trainticket was developed based on OpenFaaS version 0.12.4. You can update the function template according to your OpenFaaS version (e.g., replace the statement `compile project(':model')` with the code above).

If you have any further questions, please feel free to ask and I will help you. Thanks for reading!

**Comment by DaY1zz** [comment]
确实是这样，感谢解答！

**Comment by DaY1zz** [comment]
后续我直接使用作者的docker镜像部署后，函数间调用还是出现了Bug，不确定是否为代码问题还是镜像问题，可以加一下联系方式了解一下么？
QQ：1029464886
